DROP TABLE IF EXISTS RECIPES;
DROP TABLE IF EXISTS INGREDIENTS;
DROP TABLE IF EXISTS RECIPE_TO_INGREDIENTS;
DROP TABLE IF EXISTS RECIPE_TO_REVIEWS;
DROP TABLE IF EXISTS REVIEWS;
DROP TABLE IF EXISTS MODERATORS;
DROP TABLE IF EXISTS SUBSCRIBERS;

CREATE TABLE INGREDIENTS (
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY, 
    NAME VARCHAR(50)
);

CREATE TABLE RECIPES (
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY, 
    LINK VARCHAR(50) NOT NULL,
    VERIFIED_BY_MODERATOR CHAR(1) NOT NULL,
    MEAL VARCHAR(50) NOT NULL,
    TYPE VARCHAR(50) NOT NULL
);

CREATE TABLE REVIEWS (
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY, 
    REVIEWER_NAME VARCHAR(50) NOT NULL,
    REVIEW VARCHAR(750) NOT NULL,
    REVIEW_DATE DATE NOT NULL,
    VERIFIED_BY_MODERATOR CHAR(1) NOT NULL,
    RECIPE_ID INT NOT NULL,
    FOREIGN KEY (RECIPE_ID) REFERENCES RECIPES(ID)
);

CREATE TABLE RECIPE_TO_INGREDIENTS (
	RECIPE_ID INT NOT NULL,
    INGREDIENT_ID INT NOT NULL,
    FOREIGN KEY (RECIPE_ID) REFERENCES RECIPES(ID),
    FOREIGN KEY (INGREDIENT_ID) REFERENCES INGREDIENTS(ID)
);

CREATE TABLE RECIPE_TO_REVIEWS (
	RECIPE_ID INT NOT NULL,
    REVIEW_ID INT NOT NULL,
    FOREIGN KEY (RECIPE_ID) REFERENCES RECIPES(ID),
    FOREIGN KEY (REVIEW_ID) REFERENCES REVIEWS(ID)
);

CREATE TABLE MODERATORS (
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY, 
	USERNAME VARCHAR(50) NOT NULL, 
    PASSWORD VARCHAR(100) NOT NULL,
    NAME VARCHAR(50) NOT NULL
);

CREATE TABLE SUBSCRIBERS (
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY, 
	EMAIL VARCHAR(50) NOT NULL, 
    PASSWORD VARCHAR(100) NOT NULL,
    NAME VARCHAR(50) NOT NULL
);

